# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }

# MARKDOWN ********************

# # Perform data exploration for data science
# 
# Use the code in this notebook to perform data exploration for data science.!


# MARKDOWN ********************

# ### Carregar dados em um dataframe
# Agora você está pronto para executar o código para obter dados. Você trabalhará com o [conjunto de dados Vendas de suco de laranja](https://learn.microsoft.com/en-us/azure/open-datasets/dataset-oj-sales-simulated?tabs=azureml-opendatasets?azure-portal=true) do Azure Open Datasets. Depois de carregar os dados, você converterá os dados em um dataframe do Pandas, que é a estrutura com suporte do Data Wrangler.
# 
# - [Executar o pré-processamento de dados com Data Wrangler no Microsoft Fabric](https://microsoftlearning.github.io/mslearn-fabric.pt-br/Instructions/Labs/08b-data-science-preprocess-data-wrangler.html)

# CELL ********************

# Azure storage access info for open dataset diabetes
blob_account_name = "azureopendatastorage"
blob_container_name = "ojsales-simulatedcontainer"
blob_relative_path = "oj_sales_data"
blob_sas_token = r"" # Blank since container is Anonymous access
    
# Set Spark config to access  blob storage
wasbs_path = f"wasbs://%s@%s.blob.core.windows.net/%s" % (blob_container_name, blob_account_name, blob_relative_path)
spark.conf.set("fs.azure.sas.%s.%s.blob.core.windows.net" % (blob_container_name, blob_account_name), blob_sas_token)
print("Remote blob path: " + wasbs_path)
    
# Spark reads csv
df = spark.read.csv(wasbs_path, header=True)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

import pandas as pd

df = df.toPandas()
df = df.sample(n=500, random_state=1)
    
df['WeekStarting'] = pd.to_datetime(df['WeekStarting'])
df['Quantity'] = df['Quantity'].astype('int')
df['Advert'] = df['Advert'].astype('int')
df['Price'] = df['Price'].astype('float')
df['Revenue'] = df['Revenue'].astype('float')
    
df = df.reset_index(drop=True)
df.head(4)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# #### **Exibir estatísticas resumidas**
# 
# Agora que carregamos os dados, a próxima etapa é pré-processar os dados usando o Data Wrangler. O pré-processamento é uma etapa crucial em qualquer fluxo de trabalho de aprendizado de máquina. Ele envolve limpar os dados e transformá-los em um formato que pode ser alimentado em um modelo de machine learning.
# 
# 1   Selecione Dados na faixa de opções do notebook e, em seguida, selecione a lista suspensa Iniciar Data Wrangler.
# 
# 2   Selecione o conjunto de dados df. Quando o Data Wrangler é iniciado, ele gera uma visão geral descritiva do dataframe no painel Resumo.
# 
# 3   Selecione o recurso Receita e observe a distribuição de dados desse recurso.
# 
# _Examine os detalhes do painel lateral Resumo e observe os valores das estatísticas._
# 


# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Replace all instances of "." with "``" in column: 'Brand'
    df['Brand'] = df['Brand'].str.replace(".", "``", case=False, regex=False)
    # Capitalize the first character in column: 'Brand'
    df['Brand'] = df['Brand'].str.capitalize()
    return df

df_clean = clean_data(df.copy())
df_clean.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

def clean_data(df):
    # Replace all instances of "." with " " in column: 'Brand'
    df['Brand'] = df['Brand'].str.replace(".", " ", case=False, regex=False)
    # Capitalize the first character in column: 'Brand'
    df['Brand'] = df['Brand'].str.title()
    return df
    
df = clean_data(df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df['Brand'].unique()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ### **Aplicar transformação de codificação one-hot**
# 
# Agora, vamos gerar o código para aplicar a transformação de codificação one-hot aos nossos dados como parte de nossas etapas de pré-processamento. Para tornar nosso cenário mais prático, começamos gerando alguns dados de exemplo. Isso nos permite simular uma situação do mundo real e nos fornece um recurso viável.

# MARKDOWN ********************

# Inicie o Data Wrangler no menu superior do dataframe df.
# 
# Selecione o recurso Brand na grade.
# 
# No painel Operações, expanda Fórmulas e, a seguir, selecione Codificação one-hot.
# 
# No painel Codificação one-hot, selecione Aplicar.
# 
# Navegue até o final da grade de exibição do Data Wrangler. Observe que ele adicionou três novos recursos (Brand_Dominicks, Brand_Minute Maid e Brand_Tropicana) e removeu o recurso Brand.

# CELL ********************

#Inicie o Data Wrangler no menu superior do dataframe df.

Selecione o recurso Brand na grade.

No painel Operações, expanda Fórmulas e, a seguir, selecione Codificação one-hot.

No painel Codificação one-hot, selecione Aplicar.

Navegue até o final da grade de exibição do Data Wrangler. Observe que ele adicionou três novos recursos (Brand_Dominicks, Brand_Minute Maid e Brand_Tropicana) e removeu o recurso Brand.

Saia do Data Wrangler sem gerar o código.


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# #### **Operações de classificação e filtro**
# 
# Imagine que precisamos examinar os dados de receita de um repositório específico e classificar os preços dos produtos. Nas etapas a seguir, usamos o Data Wrangler para filtrar e analisar o dataframe df.
# 
# Inicie o Data Wrangler para o dataframe df.
# 
# No painel Operações, expanda Classificar e filtrar.
# 
# Selecione Filtro.
# 
# No painel Filtro, adicione a seguinte condição:
# 
# - Coluna de destino: Store
# - Operação: Equal to
# - Valor: 1227
# - Ação: Keep matching rows
# 


# MARKDOWN ********************

# #### **Agregação de dados**
# 
# Suponha que precisamos entender a receita média gerada por cada marca. Nas etapas a seguir, usamos o Data Wrangler para executar um grupo por operação no dataframe df.
# 
# - Inicie o Data Wrangler para o dataframe df.
# - Volte ao painel Operações, selecione Agrupar por e agregar.
# - No painel Colunas a serem agrupadas por, selecione o recurso Brand.
# - Selecione Adicionar agregação.
# - Na propriedade Coluna a ser agregada, selecione o recurso Revenue.
# - Selecione Mean para a propriedade Tipo de Agregação.
# - Escolha Aplicar.
# - Selecione Copiar código para a área de transferência.
# - Saia do Data Wrangler sem gerar o código.
# 
# Combine o código da transformação de variável Brand com o código gerado pela etapa de agregação na função clean_data(df). O bloco de código final deve ser assim
# 
# 


# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Performed 1 aggregation grouped on column: 'Brand'
    df = df.groupby(['Brand']).agg(Revenue_mean=('Revenue', 'mean')).reset_index()
    return df

df_clean = clean_data(df.copy())
df_clean.head()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

def clean_data(df):    
    # Replace all instances of "." with " " in column: 'Brand'    
    df['Brand'] = df['Brand'].str.replace(".", " ", case=False, regex=False)    
    # Capitalize the first character in column: 'Brand'    
    df['Brand'] = df['Brand'].str.title()
        
    # Performed 1 aggregation grouped on column: 'Brand'    
    df = df.groupby(['Brand']).agg(Revenue_mean=('Revenue', 'mean')).reset_index()    
        
    return df    
        
df = clean_data(df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# # Codificação One-Hot
# 
# A **codificação one-hot (One-Hot Encoding)** é uma técnica usada para transformar variáveis categóricas em um formato numérico que pode ser utilizado em modelos de Machine Learning.
# 
# ## 📌 O que é One-Hot Encoding?
# 
# Muitos algoritmos de Machine Learning não conseguem trabalhar diretamente com variáveis categóricas (como "Vermelho", "Azul", "Verde"), pois exigem dados numéricos. A codificação one-hot resolve isso criando uma nova coluna para cada categoria e atribuindo valores binários (0 ou 1) para indicar a presença daquela categoria.
# 
# ## 📊 Exemplo Prático
# 
# ### 🎨 Variável Categórica Original:
# 
# | Cor |
# |------|
# | Azul |
# | Vermelho |
# | Verde |
# | Azul |
# | Verde |
# 
# ### 🔄 Após One-Hot Encoding:
# 
# | Cor_Azul | Cor_Vermelho | Cor_Verde |
# |----------|-------------|-----------|
# | 1        | 0           | 0         |
# | 0        | 1           | 0         |
# | 0        | 0           | 1         |
# | 1        | 0           | 0         |
# | 0        | 0           | 1         |
# 
# Cada linha tem **1** na coluna correspondente à categoria original e **0** nas demais.
# 
# ## 🛠 Como Implementar no Python
# 
# Usando **pandas**:
# 
# ```python
# import pandas as pd
# 
# # Criando um DataFrame
# dados = pd.DataFrame({'Cor': ['Azul', 'Vermelho', 'Verde', 'Azul', 'Verde']})
# 
# # Aplicando One-Hot Encoding
# dados_one_hot = pd.get_dummies(dados, columns=['Cor'])
# 
# print(dados_one_hot)
# ```
# 
# ### 📌 Resultado esperado:
# ```
#    Cor_Azul  Cor_Vermelho  Cor_Verde
# 0        1            0         0
# 1        0            1         0
# 2        0            0         1
# 3        1            0         0
# 4        0            0         1
# ```
# 
# ## ⚠️ Cuidados ao Usar One-Hot Encoding
# 
# 🔹 **Explosão Dimensional**: Se a variável categórica tiver muitas categorias, o número de colunas criadas pode ser muito grande, impactando a performance do modelo.
# 
# 🔹 **Drop de uma Coluna**: Para evitar colinearidade, pode ser interessante remover uma das colunas geradas (usando `drop_first=True` no `pd.get_dummies()`).
# 
# 🔹 **Sparse Matrices**: Para grandes datasets, utilizar representações esparsas pode economizar memória.
# 
# ## 🚀 Conclusão
# 
# A codificação one-hot é uma técnica essencial para lidar com variáveis categóricas e torná-las utilizáveis por algoritmos de Machine Learning. No entanto, deve ser usada com cuidado para evitar problemas de explosão dimensional.

